apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
# Commands:
# kubectl apply -f nginx_replicaset.yaml
# kubectl expose replicaset nginx-replicaset --name=nginx-service --port=80 --type=NodePort
# minikube service nginx-service --url
