apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
# Commands:
# kubectl apply -f nginx_pod.yaml
# kubectl expose pod nginx --name=nginx-service --port=80 --type=NodePort
# minikube service nginx-service --url
