apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx-service
    app: demo-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-pod
    app: demo-app
  